name: language_pickers
description: It makes language select pickers for you in Flutter. You can use it freely in lots of ways.
version: 0.2.0+1
homepage: https://github.com/gomgom/flutter_language_pickers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  assets:
#  - assets/
